version: '3'
services:
  postgres:
    container_name: ch_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres:/var/lib/postgres
    hostname: localhost
    ports:
      - "5050:5432"
    networks:
      - cinema-hille-service

  keycloak:
    container_name: ch_keycloak
    image: quay.io/keycloak/keycloak:21.1.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    ports:
      - "8180:8080"
    networks:
      - cinema-hille-service
    depends_on:
      - postgres

  cinema-hillel-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5050/cinema
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin


volumes:
  postgres:
  keycloak:
  src:

networks:
  cinema-hille-service:

