server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5050/cinema
    username: postgres
    password: admin
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
    default-schema: public

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/CinemaHillel/protocol/openid-connect/certs
