server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: admin

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
