server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinema
    username: postgres
    password: admin
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
    default-schema: public

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
